### ISSUE TITLE
Faire Template Civil

### ISSUE THREAD

**Issue by 14eKake** [14eKake/Antistasi_14e_WW2#2]
**Demande de Création de Template pour Civils**

1. **Véhicules Civils :**
   - Exemple : `["vehiclesCivCar", ["C_Offroad_01_F","C_Offroad_01_A"]]`
   - Note : Possibilité d'ajouter plusieurs véhicules.

2. **Tenues et Équipements :**
   - Uniformes pour Civils Normaux : `private _civUniforms = [];`
   - Uniformes pour Journalistes : `private _pressUniforms = [];`
   - Uniformes pour Ouvriers (Factory) : `private _workerUniforms = [];`

3. **Attribution des Uniformes dans l'Arsenal :**
   - `["uniforms", _civUniforms + _pressUniforms + _workerUniforms + _dlcUniforms] call _fnc_saveToTemplate;`
   - Note : Cette ligne est essentielle pour fournir les uniformes aux rebelles sous couverture civile. Ne pas modifier.

4. **Chapeaux pour Civils/Ouvriers/Rebelles Cachés :**
   - Déclaration : `_civHats = [];`
   - Attribution : `["headgear", _civHats] call _fnc_saveToTemplate;`

5. **Configuration des Loadouts :**
   - Création de la structure de données de loadout : `private _loadoutData = call _fnc_createLoadoutData;`
   - Configuration des uniformes : 
     - `_loadoutData set ["uniforms", _civUniforms];`
     - `_loadoutData set ["pressUniforms", _pressUniforms];`
     - `_loadoutData set ["workerUniforms", _workerUniforms];`
   - Configuration des équipements de protection :
     - `_loadoutData set ["pressVests", []];`
     - `_loadoutData set ["helmets", _civHats];`
     - `_loadoutData set ["pressHelmets", []];`
   - Configuration des objets de navigation :
     - `_loadoutData set ["maps", ["ItemMap"]];`
     - `_loadoutData set ["watches", ["ItemWatch"]];`
     - `_loadoutData set ["compasses", ["ItemCompass"]];`

---

**Note** : Il est nécessaire que quelqu'un prenne en charge la création de ce template pour les civils.

**Comment by 14eWolfman** [comment]
caca

**Comment by 14eWolfman** [comment]
Véhicules Civils :

["vehiclesCivCar", ["LIB_GazM1","LIB_CIV_FFI_CitC4","LIB_CIV_FFI_CitC4_2","LIB_CIV_FFI_CitC4_3","LIB_CIV_FFI_CitC4_5","LIB_Zis5v_w","LIB_Zis5v_med_w"]]

**Comment by 14eWolfman** [comment]
Tenues et Équipements :

Uniformes pour Civils Normaux : private _civUniforms = ["U_GELIB_FRA_Citizen01","U_GELIB_FRA_Citizen02","U_GELIB_FRA_Citizen03","U_GELIB_FRA_Citizen04","U_GELIB_FRA_Functionary01","U_GELIB_FRA_Functionary02","U_GELIB_FRA_Woodlander01","U_GELIB_FRA_Woodlander02","U_GELIB_FRA_Schoolteacher","U_GELIB_FRA_Doctor1","U_GELIB_FRA_Doctor2","U_GELIB_FRA_Villager01","U_GELIB_FRA_CitizenFF01","U_GELIB_FRA_CitizenFF02","U_GELIB_FRA_CitizenFF03","U_GELIB_FRA_CitizenFF04","U_GELIB_FRA_WoodlanderFF01","U_GELIB_FRA_WoodlanderFF04","U_GELIB_FRA_EmployeFF","U_GELIB_FRA_AssistantFF","U_GELIB_FRA_FunctionaryFF01","U_GELIB_FRA_FunctionaryFF02","U_GELIB_FRA_VillagerFF01","U_GELIB_FRA_VillagerFF02","U_GELIB_FRA_MGunner_gvnpFF13","U_GELIB_FRA_MGunner_gvmpFF14","U_GELIB_FRA_SoldierFF_gvmpFF15","U_GELIB_FRA_SoldierFF_gvmpFF16","U_GELIB_FRA_ScoutFF_Camo31vgpFF17","U_GELIB_FRA_ScoutFF_Camo32vmpFF18","U_GELIB_FRA_SoldierFF_w31vmpFF19","U_GELIB_FRA_SoldierFF_w32vgpFF20","U_LIB_CIV_Assistant","U_LIB_CIV_Assistant_2","U_LIB_CIV_Functionary_3","U_LIB_CIV_Functionary_2","U_LIB_CIV_Functionary_4","U_LIB_CIV_Functionary_1","U_LIB_CIV_Woodlander_1","U_LIB_CIV_Woodlander_3","U_LIB_CIV_Woodlander_2","U_LIB_CIV_Woodlander_4","U_LIB_CIV_Citizen_1","U_LIB_CIV_Citizen_2","U_LIB_CIV_Citizen_3","U_LIB_CIV_Citizen_4","U_LIB_CIV_Citizen_5","U_LIB_CIV_Citizen_6","U_LIB_CIV_Citizen_7","U_LIB_CIV_Citizen_8","U_LIB_CIV_Schoolteacher","U_LIB_CIV_Schoolteacher_2","U_LIB_CIV_Doctor","U_LIB_CIV_Worker_3","U_LIB_CIV_Worker_1","U_LIB_CIV_Worker_4","U_LIB_CIV_Worker_2","U_LIB_CIV_Priest","U_LIB_CIV_Rocker_1","U_LIB_CIV_Villager_4","U_LIB_CIV_Villager_1","U_LIB_CIV_Villager_2","U_LIB_CIV_Villager_3"];

**Comment by 14eWolfman** [comment]
Chapeau Civil: 

["GEH_Beret_blue","GERDS_Beret1","GEH_Beret_blk","GEH_Chapeau_Brun","GEH_Chapeau_Gris","GEH_Chapeau_GrisClair","GEH_Chapeau_GrisFonce","GEH_Chapeau_MarronClair","GEH_Chapeau_MarronFonce","GEH_Chapeau_Noir1","GEH_Chapeau_Noir2","H_LIB_CIV_Villager_Cap_1","H_LIB_CIV_Villager_Cap_2","H_LIB_CIV_Villager_Cap_3","H_LIB_CIV_Villager_Cap_4","H_LIB_CIV_Worker_Cap_1","H_LIB_CIV_Worker_Cap_2","H_LIB_CIV_Worker_Cap_3","H_LIB_CIV_Worker_Cap_4"];

**Comment by 14eWolfman** [comment]
Accessoire civil:

["fow_g_glasses1","fow_g_glasses2","fow_g_glasses3","fow_g_gloves4","fow_g_gloves5","fow_g_gloves6","fow_g_gloves2","fow_g_gloves1","fow_g_gloves","fow_g_watch2","fow_g_watch1","fow_g_glasses4","G_GEHeadBandage_Bloody","G_GEHeadBandage_Clean","G_GEHeadBandage_Stained"]

**Comment by 14eWolfman** [comment]
Accessoire JVN:

["LIB_GER_Gloves4","LIB_GER_Gloves5","LIB_GER_Gloves2","LIB_GER_Gloves1","LIB_GER_Gloves3","N_GEHeadBandage_Bloody","N_GEHeadBandage_Clean","N_GEHeadBandage_Stained"]

**Comment by 14eWolfman** [comment]
Sac a dos:

["B_LIB_GER_Tonister34_cowhide","B_LIB_GER_MedicBackpack_Empty","B_LIB_SOV_RA_MGAmmoBag_Empty","B_LIB_SOV_RA_GasBag","B_LIB_SOV_RA_MedicalBag_Empty","B_LIB_UK_HSack","B_LIB_UK_HSack_Blanco","B_LIB_UK_HSack_Blanco_Cape","B_LIB_UK_HSack_Cape","B_LIB_UK_HSack_Blanco_Tea","B_LIB_UK_HSack_Tea"]

**Comment by 14eKake** [comment]
Importer et fonctionnel.
